country_symbol_mapping = {
    'Australia': 'au',
    'Austria': 'at',
    'Belgium': 'be',
    'Canada': 'ca',
    'China': 'cn',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Egypt': 'eg',
    'Finland': 'fi',
    'France': 'fr',
    'Germany': 'de',
    'Greece': 'gr',
    'Hungary': 'hu',
    'Indonesia': 'id',
    'Ireland': 'ie',
    'Italy': 'it',
    'Japan': 'jp',
    'South Korea': 'kr',
    'Luxembourg': 'lu',
    'Mexico': 'mx',
    'Netherlands': 'nl',
    'Norway': 'no',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Slovakia': 'sk',
    'Spain': 'es',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'Turkey': 'tr',
    'United Kingdom': 'gb',
    'United States': 'us',
    'Chile': 'cl',
    'Estonia': 'ee',
    'Israel': 'il',
    'Slovenia': 'si',
    'Iceland': 'is',
    'Latvia': 'lv',
    'Colombia': 'co',
    'Lithuania': 'lt',
    'New Zealand': 'nz',
    'Brazil': 'br',
    'Romania': 'ro',
    'Russia': 'ru',
    'Other Advanced Economies Average': 'oa',
    'OECD Countries': 'oc'
}
